import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TODO APP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <head></head>
      <body>
        <h1>Awesome Todo App</h1>
        {children}
      </body>
    </html>
  );
}
